### ISSUE TITLE
Can't install the Software - Old Estclam Version [Link]

### ISSUE THREAD

**Issue by hoellwerth** [cryinkfly/Estlcam-for-Linux#1]
![image](https://github.com/cryinkfly/Estlcam-for-Linux/assets/78997851/24ff92a0-a12a-42be-8332-fc044ad2cb13)

I Can't click OK in any way

**Comment by arisvergas** [comment]
same here

**Comment by cryinkfly** [comment]
It is solved by updated the version link of Estclam!

**Comment by nZambi-** [comment]
Hey, just a bump as the version has changed again and the installer is hanging for me as well now. As of now the link is-
https://www.estlcam.de/downloads/Estlcam_64_12119.exe
I tried to simply change the link myself in the installer but it is still failing.

**Comment by RumpelbumpelX** [comment]
You have to change line 554 from "SP_SELECT_ESTCLAM_VERSION" to "SP_SELECT_ESTCLAM" then it works.

**Comment by bernieke** [comment]
That fix indeed gets it to install!

Unfortunately estlcam crashes when it starts showing its UI (I see the logo, then the UI with menu bar comes up, and immediately goes away again).

I'll just use a virtual machine to run it...

**Comment by bernieke** [comment]
Got the latest version to install on arch by simply running:
```
yay -S winetricks
winetricks dotnet48 gdiplus d3dx9_36
wine Estlcam_64_12125.exe
```

Unfortunately, probably due to my using awesome wm, it's not really workable. When navigating the menus, they autoclose after half a second (probably when there would normally be a popup with information, but the loss of focus closes the menu as well as the popup). So a VM it will have to be.
